### ISSUE TITLE
Random crash, game randomly unresponsive near DL50. [Crash]

### ISSUE THREAD

**Issue by SilearFlare** [earlfogel/UltraRogue#2]
I cannot give more information: Halfway through the game (around I think DL 48 or 49) while battling some random mobs in a room, the interface simply stopped working and the game became unresponsive. Trying to save the game was impossible and as such my only option was to close the terminal and lose my save.

I'm attaching the latest available screenshot of the crash.
![Screenshot from 2020-05-25 18-54-52](https://user-images.githubusercontent.com/5557920/82831723-81ada280-9eb9-11ea-8fef-711b130b0cd9.png)

It would be nice if there was a possibility to back up your save in the background with every level, to prevent it from happening again.

**Comment by earlfogel** [comment]
Hi,

I see from the screenshot that the lockup happened when you were standing by a door. There was an issue in early April where a dying monster could drop items on top of a door, which could cause the game to crash.  This was fixed on April 5.  If you downloaded the game before then, this is probably the one you ran into.

I fixed another lockup issue on May 9 in the wandering monster code, but as far as I can see that would only happen in trading posts and monster lairs.

If this happened in a more recent version of the code, please let me know and I'll look into it some more.

**Comment by SilearFlare** [comment]
No, I can confirm that happened around April, I just got around posting these. Thank you for the reply! I will close this issue.
