### ISSUE TITLE
Purse of Yendor remaps items which cannot be retrieved, are forever lost [Bug or Feature?] 

### ISSUE THREAD

**Issue by SilearFlare** [earlfogel/UltraRogue#3]
When using the purse of yendor, at that a certain point when filling it any item could be remapped with a question mark. The item cannot be retrieved anymore and this can happen with any item in the bag. In my case, it was a particularly unlucky choice to put all my food into my bag of holding.
![Screenshot from 2020-05-25 19-04-55](https://user-images.githubusercontent.com/5557920/82832369-25e41900-9ebb-11ea-97c5-3742baeee0d2.png)

If this is an intended side effect of the bag (having it lose some of your items as not to be able to stock up on every single valuable consumable in the dungeon) then it's actually working great.

**Comment by earlfogel** [comment]
I've fixed a bug that could cause this.  Normally the purse is limited to 23 items, but I increased that limit in easy games.  If you fill the purse in an easy game and then change the difficulty level, you can end up with more than the maximum allowed.  Once you've done that, the bug would let you keep adding more items and the game would run out of letters for them, and would use question marks instead.

I also fixed a second bug involving the purse.  When you add food to the purse, it all gets grouped together and shows as a single item.  But when you add it a bit at a time, the bug would count each addition separately, reducing the total number of items the purse could hold.

**Comment by SilearFlare** [comment]
Wonderful, thanks for the hard work!
