### ISSUE TITLE
Maze level trap generates labyrinths that scale with monitor/ terminal font size: nearly all characters die of starvation before finding exit

### ISSUE THREAD

**Issue by SilearFlare** [earlfogel/UltraRogue#4]
This can be especially hard on sub-20p fonts and 1080p monitors, but even with the largest possible font-terminal size combo that still lets me render the UI entirely (and thus play the game properly) I went from completely full to starving before I managed to explore the entire level and found the staircase.
![Screenshot from 2020-05-28 22-28-48](https://user-images.githubusercontent.com/5557920/83190727-27b81180-a133-11ea-9dea-410789ab4522.png)

As it is, even with the best precautions it seems like this specific trap is guaranteed death sentence instead of a minor annoyance.

Thanks in advance as always for any help with this issue.

**Comment by earlfogel** [comment]
Yeah, the amount of food on each level is random, but (like monsters and treasure) does increase  deeper in the dungeon, so starvation is usually only a problem early in the game.

There are a few things you can do in this situation.

First, the amount of food you need increases based on how much weight you are carrying, starting at 60% of your carrying capacity, and it looks like you were just over 60% in the screen shot.

Some rings burn through food too -- the worst are regeneration, vampiric regeneration, alertness and sustain ability.

There are a few ways to get through mazes more quickly.  Magic mapping will show you the location of the stairs; illumination spells, scrolls, wands and rings let you see further, so you can move through the maze more quickly.  A blessed scroll of teleportation will take you to another level.
A potion of phasing can help too.

There is one simple trick to getting out of a maze, but it took me years to find it.  I'll encode it with rot13 below, so you can decide if you want to decode it or look for it on your own.

Good luck!

Earl
--
Hfr gur '^' pbzznaq gb frg n genc qbbe, gura jnyx vagb vg.
--

**Comment by SilearFlare** [comment]
Thank you very much for the helpful tips and the spoiler, I'll get back to that eventually if I start getting hungry in a maze with no food left!
