### ISSUE TITLE
Allow diagonal movement when running and opening doors

### ISSUE THREAD

**Issue by jv84** [earlfogel/UltraRogue#6]
Why not?

**Comment by earlfogel** [comment]
There is a 'cutcorners' option that lets you move diagonally through doors and around corners.  Is that what you mean?

**Comment by jv84** [comment]
Yes, exactly that. But running diagonally or even autotraveling would be cool.

**Comment by jv84** [comment]
Actually it seems that running in corridors doesn't work sometimes.

**Comment by earlfogel** [comment]
You can walk diagonally using the y, u, b and n keys, and run using Y, U, B and N (and ^Y, ^U, ^B and ^N).  Don't those work?

If you use the keypad for movement, then the shift and control movement keys may or may not work because the ncurses library doesn't support them consistently.  I think this is the only area where the game works better with PDcurses on Windows than it does with ncurses on Linux.

I haven't run into any issues with running in corridors.  Can you provide any more details?

**Comment by jv84** [comment]
> You can walk diagonally using the y, u, b and n keys, and run using Y, U, B and N (and ^Y, ^U, ^B and ^N). Don't those work?

They work.

> If you use the keypad for movement, then the shift and control movement keys may or may not work because the ncurses library doesn't support them consistently. I think this is the only area where the game works better with PDcurses on Windows than it does with ncurses on Linux.

ncurses doesn't support modifier keys.

> I haven't run into any issues with running in corridors. Can you provide any more details?

Maybe this is related to ncurses too. I really hate to use alphabet keys for moving.

P.S. This might be related too. When I press 'w' and then press Esc twice, the game unwields the weapon. Is this intentional?
Also "Illegal command" is displayed when using modifier keys the wrong way.

**Comment by jv84** [comment]
All of these things must be Curses issues.

**Comment by earlfogel** [comment]
I've just added a hack to support using CTRL with the keypad movement keys with ncurses.

There's an "#ifdef EARL ... #endif" around this code as it may break things.  To try it out, download the latest code and add "-DEARL" to the CFLAGS in the Makefile.

**Comment by earlfogel** [comment]
Yes, pressing ESC to unwield a weapon is intentional, because the only other way I've found to do it is to drop the weapon.

**Comment by jv84** [comment]
> I've just added a hack to support using CTRL with the keypad movement keys with ncurses.
> 
> There's an "#ifdef EARL ... #endif" around this code as it may break things. To try it out, download the latest code and add "-DEARL" to the CFLAGS in the Makefile.

It doesn't work.

**Comment by jv84** [comment]
> Yes, pressing ESC to unwield a weapon is intentional, because the only other way I've found to do it is to drop the weapon.

ESC should exit the menu. Add a key to unwield the weapon?

Double pressing ESC is annoying!

**Comment by jv84** [comment]
Why the help key asks for a character? Is it really needed?

**Comment by jv84** [comment]
I'm not going to contribute to this project any further if the user interface is not radically improved.
Having every 80's terminal glitch in 2020 is a real nightmare.

**Comment by earlfogel** [comment]
I'm sorry to hear that, but I understand how you feel.

The reason for the two-character help is that urogue was written in the days of old slow terminals, where refreshing the entire window was painfully slow.  Typing '?d' for help on the 'd' command avoids a full refresh.

Thanks for your feedback about ESC.  I'll change that.
