### ISSUE TITLE
Fix compiler warnings

### ISSUE THREAD

**Issue by jv84** [earlfogel/UltraRogue#7]
warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]

fread

FIX:
(void) !fread

warning: format not a string literal and no format arguments [-Wformat-security]

printf(usage);

FIX:
printf("%s", usage);

**Comment by jv84** [comment]
fread's return value should be obviously handled somehow.

**Comment by earlfogel** [comment]
Done. I've fixed all gcc -Wextra and -Wformat=2 warnings.
